# Generated by Django 2.2.6 on 2019-11-19 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldofstudies',
            name='slug',
            field=models.SlugField(default='slug', help_text='Slug which identifies field of study in syllabus', unique=True),
            preserve_default=False,
        ),
    ]
