# Generated by Django 2.2.6 on 2020-03-16 23:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0008_auto_20200311_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fieldofstudyofagegroup',
            name='field_of_study',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name='field_age_groups',
                to='subject.FieldOfStudy',
            ),
        ),
    ]
