# Generated by Django 2.2.6 on 2020-04-02 10:51

from django.db import migrations, models
from django.utils.crypto import get_random_string


def set_random_module_code(apps, schema_editor):
    """Set random module code on subjects"""
    subjects = apps.get_model("subject", "Subject").objects.filter(
        module_code__isnull=True
    )
    for subject in subjects:
        subject.module_code = get_random_string()
        subject.save()


class Migration(migrations.Migration):

    dependencies = [
        ("subject", "0009_auto_20200316_2300"),
    ]

    operations = [
        migrations.AddField(
            model_name="subject",
            name="module_code",
            field=models.CharField(max_length=50, unique=False, null=True),
            preserve_default=False,
        ),
        migrations.RunPython(set_random_module_code),
        migrations.AlterField(
            model_name="subject",
            name="module_code",
            field=models.CharField(max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="subject",
            name="category",
            field=models.CharField(default="Ogólny", max_length=100),
            preserve_default=False,
        ),
    ]
