# Generated by Django 2.2.6 on 2021-02-12 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subject", "0010_subject_syllabus_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="resource",
            name="image",
            field=models.ImageField(blank=True, upload_to=""),
        ),
        migrations.AlterModelOptions(
            name="fieldofstudy",
            options={
                "verbose_name": "Field of study",
                "verbose_name_plural": "Fields of study",
            },
        ),
        migrations.AlterModelOptions(
            name="fieldofstudyofagegroup",
            options={
                "verbose_name": "Field of study (age group)",
                "verbose_name_plural": "Fields of study (age group)",
            },
        ),
        migrations.AlterModelOptions(
            name="subjectofagegroup",
            options={
                "verbose_name": "Subject (age group)",
                "verbose_name_plural": "Subjects (age group)",
            },
        ),
    ]
