# Generated by Django 2.2.6 on 2020-04-30 18:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0006_auto_20200314_2220'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('other', models.FileField(blank=True, null=True, upload_to='', verbose_name='files/')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='images/')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='file_created', to='accounts.UserProfile')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='file_modified', to='accounts.UserProfile')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
