# Generated by Django 2.2.6 on 2020-04-30 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
        ('subject', '0010_subject_syllabus_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='files',
            field=models.ManyToManyField(blank=True, to='files.File'),
        ),
    ]
