const EVENT_TYPES = [
  'EXAM',
  'MID_TERM_EXAM',
  'PROJECT',
  'OTHER'
];

const RESOURCE_TYPES = [
  'LECTURE',
  'EXAM',
  'MID_TERM_EXAM',
  'OTHER'
];

const SEMESTERS = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10];

const USER_TYPES = {
  REPRESENTATIVE: 1,
  MODERATOR: 2,
  NORMAL: 3
};

export { EVENT_TYPES, RESOURCE_TYPES, SEMESTERS, USER_TYPES };
