version: '3'

services:
  web:
    restart: always
    build: .
    expose:
      - "8000"
    ports:
      - "8000:8000"
    links:
      - postgres:postgres
      - redis:redis
    environment:
      POSTGRES_HOST: postgres
    env_file:
      - .local-env
    command: bash -c "python manage.py migrate && python manage.py runserver 0:8000"
    depends_on:
      - postgres

  postgres:
    restart: always
    image: postgres:11-alpine
    ports:
      - "5432:5432"
    env_file:
      - .local-env
    volumes:
      - pgdata:/var/lib/postgresql/data/

  redis:
    image: 'redis:5.0.8-alpine'
    ports:
      - '6379:6379'
    volumes:
      - 'redisdata:/data'

volumes:
  pgdata:
  redisdata:
