[tool.isort]
profile = "black"

[tool.coverage.report]
branch = true
exclude_lines = [
    "pragma: no cover",
    "if TYPE_CHECKING:"
]
omit = [
    "**/fixtures.py",
    "manage.py",
    "**/wsgi.py",
    "**/settings/*.py",
    "**/migrations/*.py",
]

[tool.pytest.ini_options]
DJANGO_SETTINGS_MODULE = "passit.settings.local"
python_files = ["tests.py", "test_*.py", "*_tests.py"]
norecursedirs = ["deployment*",
                 ".git/*",
                 ".mypy_cache/*",
                 ".pytest_cache/*",
                 "migrations/*",
                 "passit/frontend/*"
]
addopts = "--nomigrations"
[tool.tox]
legacy_tox_ini = """
[tox]
envlist = py38, flake8, black, isort, mypy
skipsdist = True

[gh-actions]
python =
    3.8: py38

[testenv:flake8]
basepython = python
deps = flake8
commands = flake8 --format=default passit

[testenv:black]
deps = black
commands = black --check passit

[testenv:isort]
deps = isort
commands = isort --check passit

[testenv:mypy]
deps = -r requirements/dev.txt
commands = mypy passit

[testenv]
setenv = PYTHONPATH = {toxinidir}
deps = -r requirements/dev.txt
commands = pytest passit
"""
