workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: projekt

version: 2
jobs:
  build:
    working_directory: ~/teleagh
    docker:
      - image: circleci/python:3.7.6
        environment:
          DATABASE_URL: postgresql://postgres@localhost/circle_test?sslmode=disable
      - image: circleci/postgres:9.6.2
        environment:
          POSTGRES_USER: postgres
          POSTGRES_DB: circle_test
    steps:
      - checkout
      - run: sudo chown -R circleci:circleci /usr/local/bin
      - run: sudo chown -R circleci:circleci /usr/local/lib/python3.7/site-packages
      - restore_cache:
          keys:
            - v2-dependencies-{{ checksum "requirements.txt" }}
      - run:
          name: Install CI requirements
          command: pip install -r requirements-ci.txt
      - run:
          name: Running linter
          command: python -m flake8
      - run:
          name: install core requirements
          command: pip install -r requirements.txt
      - run:
          name: Running type checker
          command: python -m mypy .
      - save_cache:
          paths:
            - '/usr/local/lib/python3.7/site-packages'
          key: v1-dependencies-{{ checksum "requirements.txt" }}-{{ checksum "requirements-ci.txt" }}
      - run:
          name: Running tests
          command: python -m pytest
  deploy:
    docker:
      - image: alpine/git
    steps:
      - checkout
      - run:
          name: Deploy Master to Heroku
          command: |
            git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git master
