version: 2
jobs:
  build:
    working_directory: ~/teleagh
    docker:
      - image: circleci/python:3.7.3
        environment:
          DATABASE_URL: postgresql://postgres@localhost/circle_test?sslmode=disable
      - image: circleci/postgres:9.6.2
        environment:
          POSTGRES_USER: postgres
          POSTGRES_DB: circle_test
    steps:
      - checkout
#      - run: sudo chown -R circleci:circleci /usr/local/bin
#      - run: sudo chown -R circleci:circleci /usr/local/lib/python3.7/site-packages
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements.txt" }}
      - run:
          name: install requirements
          command: pip install -r requirements.txt
      - save_cache:
          paths:
            - '/usr/local/lib/python3.7/site-packages'
          key: v1-dependencies-{{ checksum "requirements.txt" }}
      - run:
          name: Running linter
          command: |
            pip install flake8
            flake8
      - run:
          name: Running type checker
          command: |
            pip install -r requirements-ci.txt
            mypy .
      - run:
          name: Running tests
          command: pytest