# Generated by Django 2.2.6 on 2020-03-28 20:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_news_attachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='subject_group',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='news',
                to='subject.SubjectOfAgeGroup',
            ),
        ),
    ]
