# Generated by Django 2.2.6 on 2020-02-11 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0004_auto_20200210_1518'),
        ('accounts', '0002_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='own_field_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='representatives', to='subject.FieldOfStudyOfAgeGroup'),
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='subject.FieldOfStudyOfAgeGroup')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='accounts.UserProfile')),
            ],
        ),
        migrations.AddField(
            model_name='userprofile',
            name='field_groups',
            field=models.ManyToManyField(blank=True, related_name='students', through='accounts.Membership', to='subject.FieldOfStudyOfAgeGroup'),
        ),
    ]
