# Generated by Django 2.2.6 on 2019-11-05 22:15
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("lecturers", "0001_initial"),
        ("subject", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="lecturerofsubject",
            name="subject_group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subject_groups",
                to="subject.SubjectOfAgeGroup",
            ),
        ),
    ]
