# Generated by Django 2.2.6 on 2020-03-08 18:25

from django.db import migrations

import passit.accounts.models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_auto_20200229_1658"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="customuser",
            managers=[
                ("objects", passit.accounts.models.CustomUserManager()),
            ],
        ),
    ]
