# Generated by Django 2.2.6 on 2020-02-09 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile'),
        ('subject', '0002_fieldofstudies_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjectofagegroup',
            name='representative',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='own_group', to='accounts.UserProfile'),
        ),
    ]
